# Generated by Django 4.2.4 on 2023-08-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('venue', models.CharField(max_length=100)),
                ('venueaddress', models.CharField(max_length=100)),
                ('datatime', models.CharField(default=0, max_length=100)),
                ('contactnumber', models.BigIntegerField()),
                ('entryfee', models.BigIntegerField()),
            ],
            options={
                'db_table': 'addevent',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administration',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Eventmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'eventmanager',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.BigIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('addevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.addevent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.customer')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Bookevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.BigIntegerField()),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('addevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.addevent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.customer')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
